
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jun 24 13:34:48 CDT 2019
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 19;
  public static final int Otro_caso = 8;
  public static final int Escribe = 33;
  public static final int Coma = 12;
  public static final int Llave_c = 26;
  public static final int Op_booleano = 22;
  public static final int Llave_a = 25;
  public static final int T_dato = 4;
  public static final int Bucle = 11;
  public static final int Corchete_c = 28;
  public static final int Corchete_a = 27;
  public static final int Division = 17;
  public static final int Ejecutar = 29;
  public static final int Cadena = 6;
  public static final int Parentesis_c = 24;
  public static final int Parentesis_a = 23;
  public static final int EOF = 0;
  public static final int P_coma = 30;
  public static final int Durante = 10;
  public static final int Yes = 7;
  public static final int error = 1;
  public static final int Mensaje = 32;
  public static final int Linea = 2;
  public static final int Op_atribucion = 20;
  public static final int ERROR = 35;
  public static final int Op_logico = 18;
  public static final int Haz = 9;
  public static final int Identificador = 31;
  public static final int Resta = 15;
  public static final int Multiplicacion = 16;
  public static final int Ent = 5;
  public static final int Op_incremento = 21;
  public static final int Numero = 34;
  public static final int Suma = 14;
  public static final int Igual = 13;
  public static final int Comillas = 3;
}

